### ISSUE TITLE
Errors in UT IfcCourse 

### ISSUE THREAD

**Issue by BernhardWehrle** [bSI-InfraRoom/IFC-infra-unit-test#100]
Hallo all

When i check the unittest-file IfcCourse with the IfcChecker i got 2 errors.
Can you tell me how to solve this?
![image](https://user-images.githubusercontent.com/38724767/114671938-e7d72a00-9d04-11eb-9257-2ad918c316e9.png)

**Comment by AlexBrad1eyCT** [comment]
Hi bernhard, i think i have identified the issue in the schema and posted to the spec repository for resolution, this should then be updated back to the checker.

**Comment by pjanck** [comment]
Fixed in the IFC-Specification repository. @BernhardWehrle can you please merge in the main from the official repository and restart the checker? You can contact me directly if you need assistance.
