### ISSUE TITLE
TIN Breaklines seem weird

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-infra-unit-test#111]
Reading in Georeferencing-Tin-12d-2 in TUM OpenInfraPlatform, I get some weird breaklines:

![Georeferencing-Tin-12d-2_top_left_front](https://user-images.githubusercontent.com/59165496/116000470-a4c46300-a5f0-11eb-82e2-c905b8545fb6.png)

Is this expected?

**Comment by LeeGregory12d** [comment]
A new Tin has been uploaded which hopefully fixes the problem
