### ISSUE TITLE
DrainageSystem-2

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-infra-unit-test#18]
Tracker for https://github.com/bSI-InfraRoom/IFC-infra-unit-test/tree/main/DrainageSystem-2

**Comment by larswik** [comment]
Dataset from Aplitop. I had a few validation errors:
-	I think that the RelatedObjectsType attribute for IfcRelAssignsToGroup shall be .PRODUCT. since it refers to the type of content (RelatedObjects) in the group.
-	IfcDistributionPort #362 and #368 violates the ConnectedFrom inverse S[0:1] cardinality restriction since they are referenced more than once by IfcRelConnectsPorts.RelatedPort

**Comment by larswik** [comment]
From Juha:
Elements/Ports/Connectivity:

-	Some elements in LandXML (structures at ditch bends) do not need to be modelled as physical elements, but each pipe segment shall have a port at both ends to provide proper connectivity.
-	The 3-way connections (culvert to ditches) might be best modelled as IfcPipeFitting. JUNCTION. with three ports. 
-	For next step (next UT?, might consider modelling the ditches that now have several pipe segments using just one, but their geometry being sectioned.

Geometry:

-	Body or Axis shape representation (or both) for the culvert?
-	Extruded surface (IfcSurfaceOfLinearExtrusion) or solid (IfcExtrudedAreaSolid), or polyline for ditches? 
-	Consider testing also IfcSectionedSurface with IfcArbitraryOpenProfileDef (perhaps another UT)

**Comment by javierNadal** [comment]
I'm not sure about this UT. I would like get some confirmation if I'm right.

I see six IfcDistributionPort. 
From LandXML Struct entities with names 10, 40, 52, 122, 201 and 221.
Structs with "Ditch bend" descripton are not necesary.

One IfcPipeSegment under road (LandXML Pipe 120) that connects 10 and 122 IfcDistributionPorts

And two IfcPipeFitting.JUNTION:
	Left Side ditch (LandXML Pipes 50, 104, 116 8):
		Source: IfcDistributionPort 40 and 52
		Destination: IfcDistributionPort 10
	Right Side ditch (LandXML Pipes 204, 206, 213, 219):
		Source:	IfcDistributionPort 122 and 201
		Destination: IfcDistributionPort 221

**Comment by larswik** [comment]
After discussion with Juha:
It is enough to use the ditches on one side plus the culvert
The structure could be (for one side plus culvert):
- 2 IfcPipeSegment (PredefinedType=USERDEFINED, ObjectType=”DITCH”). Nesting one port at each end (unconnected ports at the “outer” ends). Geometry can be IfcPolyline (IfcShapeRepresentation.RepresentationIdentifier=”Axis” and RepresentationType=”Curve3D”)
- 1 IfcPipeSegment (PredefinedType=CULVERT) for the culvert. Geometry can be IfcPolyline (IfcShapeRepresentation.RepresentationIdentifier=”Axis” and RepresentationType=”Curve3D”). There could also be a solid representation, e.g. IfcExtrudedAreaSolid/IfcFixedReferenceSweptAreaSolid? (RepresentationIdentifier=“AdvancedSweptSolid”)
- One IfcDistributionChamberElement at the ditch end of the culvert (PredefinedType=USERDEFINED, ObjectType=”Ditch”). Nesting three ports, one connected to the culvert element and the others connecting to the ditch elements

I will update the unit test description accordingly as well.

**Comment by javierNadal** [comment]
Hello

I have a preliminar version. I've done a network like "H" capital letter. 

Horizontal segment is IfcPipeSegment (PredefinedType=CULVERT), with one IfcDistributionChamberElemen in each endpoint.
Then 2 IfcPipeSegment (PredefinedType=USERDEFINED, ObjectType=”DITCH”) on left, and 2 2 IfcPipeSegment (PredefinedType=USERDEFINED, ObjectType=”DITCH”) on right. Validation with KIT ifcCheckingTool looks right.

By now, there is no representation. I will add it on Monday.

I have append network to old UT_SpatialStructure_4.ifc (IFC4x3_RC2) file, and included network in #165=IFCFACILITYPART(Sammalammintie Road2 intersection)
Does anyone have a new IFC4x3_RC3 compliant version of UT_SpatialStructure_4.ifc? If not, I will try to update it by hand.

[Drainage2.zip](https://github.com/bSI-InfraRoom/IFC-infra-unit-test/files/6287336/Drainage2.zip)

**Comment by javierNadal** [comment]
SpatialStructure_4.ifc with Drainage, representation only with polylines
[DrainageSystem_2.zip](https://github.com/bSI-InfraRoom/IFC-infra-unit-test/files/6303094/DrainageSystem_2.zip)

**Comment by pjanck** [comment]
Got merged in #99
