### ISSUE TITLE
IfcCheckingTool_Lite

### ISSUE THREAD

**Issue by BernhardWehrle** [bSI-InfraRoom/IFC-infra-unit-test#61]
Hi all

is there already a new IfcCheckingTool from KIT for IFC4.3RC2 available

**Comment by pjanck** [comment]
Hi Bernhard,

the current checking tool supports IFC4x3_RC2, while we're still finishing up IFC4x3_RC3. Be sure to join us for the next software vendor workshop this Wednesday. If you haven't received the invite, make sure to contact [InfraRoom admin](mailto:infrastructure@buildingsmart.org).

**Comment by pjanck** [comment]
The IFC4x3_RC3 checker is available here: https://www.iai.kit.edu/downloads/Informatik%20f%c3%bcr%20die%20Energiesystemanalyse/IfcCheckingTool_V2.2_Build94.zip

It has also been incorporated in the checking procedure with #67.

**Comment by pjanck** [comment]
New version: https://www.iai.kit.edu/downloads/Informatik%20f%c3%bcr%20die%20Energiesystemanalyse/IfcCheckingTool_Lite_V2.2_Build-95_bs.zip

**Comment by pjanck** [comment]
New version: https://www.iai.kit.edu/downloads/Informatik%20f%c3%bcr%20die%20Energiesystemanalyse/IfcCheckingTool_Lite_V2.2_Build-95_bs.zip
