### ISSUE TITLE
IfcCurvSegment -> Geometric part of Alignment

### ISSUE THREAD

**Issue by BernhardWehrle** [bSI-InfraRoom/IFC-infra-unit-test#63]
How must I interpreate SegmentStart in the geometry part of the alignment. Is it the distancealong? I can only put in a numerical value, not a point?
![IfcCurveSegement](https://user-images.githubusercontent.com/38724767/110426905-2f83e980-80a7-11eb-904c-97a4be811a7a.png)

**Comment by pjanck** [comment]
You should use an `IfcParameterValue` for negative lengths along the parent curve, and an `IfcNonNegativeLengthMeasure` for non-negative lengths along the parent curve. With it, a point is uniquely defined on the `ParentCurve`.
