### ISSUE TITLE
Checks throwing confusing error

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-infra-unit-test#64]
the Ifc checking results are throwing an error I do not understand what is wrong with it. This relates to checking of SpatialStructure-6-3-RC2.ifc in pull request #62

```
<MVDMessage>
      <MessageType>ERROR</MessageType>
      <MVDType>SCHEMADEFINITION</MVDType>
      <MessageCode>SYNTAX_VALIDATION_1</MessageCode>
      <Instance>#46596=IFCTRANSPORTELEMENTTYPE('0a5MZ59PD0wwcMc0ilz4oQ',&#36;,'RHD_GM_Vessel:RHD_GM_Vessel',&#36;,&#36;,&#40;#46593,#46590&#41;,&#40;#46598&#41;,'339908',&#36;,VEHICLEMARINE)</Instance>
      <InstanceLink></InstanceLink>
      <Messages>
        <MessageString> incompatible operand types 'PredefinedType' = '_enum_literal'&#10;First Operand: OID: #46596&#10;Type: IfcTransportElementType&#10;References: SELFVEHICLEMARINE&#10;Type: IfcTransportElementNonFixedTypeEnum&#10;Second Operand: USERDEFINED&#10;Type: IfcTransportElementFixedTypeEnum&#10;in file ..&#92;ifc_schemata&#92;ifc4x3_rc2.exp at line 11842&#10;</MessageString>
      </Messages>
</MVDMessage>
```

I think there is an error in the tool as I see nothing wrong with the syntax...

**Comment by pjanck** [comment]
My guess: it is perhaps having difficulties in the new Select OF(enum) - I need to double check that.

**Comment by AlexBrad1eyCT** [comment]
Probably, but note it is only doing it on `IfcTransportElement` but not `IfcFacilityPart`, and it references the where rule also

**Comment by pjanck** [comment]
Perhaps this could help decipher:

http://github.com/bSI-InfraRoom/IFC-Specification/blob/master/IFC4x3_RC3.exp#L11805-L11822

**Comment by pjanck** [comment]
I assume that the WHERE rule needs better specification.

**Comment by AlexBrad1eyCT** [comment]
The rules seem correct and the model adheres to them. I'm drawn to `SELFVEHICLEMARINE` that does not seem write In the tool evaluation

**Comment by pjanck** [comment]
True. This does seem weird. 

I've notified @arch1501 - he's going to provide us with a newer version of the checker, so perhaps the problem will disappear on its own.

**Comment by pjanck** [comment]
Care to check again after #67 got merged?

**Comment by AlexBrad1eyCT** [comment]
@pjanck  Ummm the new one is worse.... sorry for the bluntness!

throwing errors on all my RC3 files around Select of Enums for example line in File:

`#29= IFCFACILITYPART('0Xy$e10wb5o9hdIM8SFQKS',#6,'Land Field',$,$,#28,$,$,$,IFCMARINEPARTTYPEENUM(.LANDFIELD.),.REGION.);`

the checker identifies this error:
```
<MVDMessage>
      <MessageType>ERROR</MessageType>
      <MVDType>SCHEMADEFINITION</MVDType>
      <MessageCode>SYNTAX_VALIDATION_1</MessageCode>
      <GUID>0Xy$e10wb5o9hdIM8SFQKS</GUID>
      <Instance>#29=IFCFACILITYPART('0Xy$e10wb5o9hdIM8SFQKS',#6,'Land Field',$,$,#28,$,$,$,LANDFIELD,REGION)</Instance>
      <InstanceLink></InstanceLink>
      <ObjectInstance>#29=IFCFACILITYPART('0Xy$e10wb5o9hdIM8SFQKS',#6,'Land Field',$,$,#28,$,$,$,LANDFIELD,REGION
      </ObjectInstance>
      <ObjectInstanceLink></ObjectInstanceLink>
      <Messages>
        <MessageString> incompatible operand types 'PredefinedType' = '_enum_literal'
First Operand: OID: #29
Type: IfcFacilityPart
References: SELFLANDFIELD
Type: IfcMarinePartTypeEnum
Second Operand: USERDEFINED
Type: IfcRailwayPartTypeEnum
in file ..&#92;ifc_schemata&#92;ifc4x3_rc3.exp at line 6746
      </MessageString>
      </Messages>
</MVDMessage>
```

for some reason the tool stripped out the typing on the enum. which is causing the error

**Comment by AlexBrad1eyCT** [comment]
Also, it only checks my RC3 files, I have a set of RC3 files and RC2 files in the request. is it able to check both??

**Comment by pjanck** [comment]
It appears that we're having a problem with the Select(Enum) structure that was coined for these entities. I'm not sure how to address this correctly. Perhaps we need to change the way the Where clause is formulated?

The procedure can only check RC3 files. RC2 files are not needed and should not be produced anymore - why would you like to check them?

**Comment by AlexBrad1eyCT** [comment]
>  Perhaps we need to change the way the Where clause is formulated?

I triple checked the EXPRESS ISO and the where rules are correctly defined...

> why would you like to check them?

Comparison of error outputs. The RC2 checker only errored IfcTransportElement.
EDIT: Realised that this is because it didn't have where rules!

**Comment by AlexBrad1eyCT** [comment]
So, I think the checker is having issues in the operand miss match in the where rules

**Comment by larswik** [comment]
I can add similar when checking my SpatialStructure_4 after updating to RC3:

**For all facility parts:**

_incompatible operand types 'PredefinedType' = '_enum_literal' First Operand:  OID: #276 Type: IfcFacilityPart References: SELFROADSEGMENT Type:  IfcRoadPartTypeEnum Second Operand: USERDEFINED Type: IfcBridgePartTypeEnum in  file ..\ifc_schemata\ifc4x3_rc3.exp at line 6746_

_incompatible operand types 'PredefinedType' = '_enum_literal' First Operand:  OID: #276 Type: IfcFacilityPart References: SELFROADSEGMENT Type:  IfcRoadPartTypeEnum Second Operand: USERDEFINED Type: IfcRailwayPartTypeEnum in  file ..\ifc_schemata\ifc4x3_rc3.exp at line 6746_

_incompatible operand types 'PredefinedType' <> '_enum_literal' First  Operand: OID: #276 Type: IfcFacilityPart References: SELFROADSEGMENT Type:  IfcRoadPartTypeEnum Second Operand: USERDEFINED Type:  IfcFacilityPartCommonTypeEnum in file ..\ifc_schemata\ifc4x3_rc3.exp at line  6746_

_incompatible operand types 'PredefinedType' <> '_enum_literal' First  Operand: OID: #276 Type: IfcFacilityPart References: SELFROADSEGMENT Type:  IfcRoadPartTypeEnum Second Operand: USERDEFINED Type: IfcMarinePartTypeEnum in  file ..\ifc_schemata\ifc4x3_rc3.exp at line 6746_

_incompatible operand types 'PredefinedType' = '_enum_literal' First Operand:  OID: #276 Type: IfcFacilityPart References: SELFROADSEGMENT Type:  IfcRoadPartTypeEnum Second Operand: USERDEFINED Type:  IfcFacilityPartCommonTypeEnum in file ..\ifc_schemata\ifc4x3_rc3.exp at line  6746_

**Comment by SergejMuhic** [comment]
Testing with Andreas to see where the checker encounters problems. Before we had a noncorrect type check, now we have a false WR CorrectPredefinedType. There was some progress but did not solve the issue yet.

**Comment by pjanck** [comment]
The checker got updated. Can you please merge the `main` branch and try again?

**Comment by AlexBrad1eyCT** [comment]
@pjanck Got a new variation on this error:

```
<MVDMessage>
      <MessageType>ERROR</MessageType>
      <MVDType>SCHEMADEFINITION</MVDType>
      <MessageCode>IFCTRANSPORTELEMENTTYPE.CORRECTPREDEFINEDTYPE</MessageCode>
      <Instance>#46596=IFCTRANSPORTELEMENTTYPE('0a5MZ59PD0wwcMc0ilz4oQ',$,'RHD_GM_Vessel:RHD_GM_Vessel',$,$,(#46590,#46593),(#46598),'339908',$,VEHICLEMARINE)</Instance>
      <InstanceLink></InstanceLink>
      <Messages>
        <MessageString> where rule 'IFCTRANSPORTELEMENTTYPE.CORRECTPREDEFINEDTYPE' evaluates to FALSE</MessageString>
      </Messages>
    </MVDMessage>
```

With Relating Error:
```
<MVDEccoMessage>
      <EccoErrorCode>37</EccoErrorCode>
      <EccoErrorMessage>
            integrity constraint violation: where rule 'IFCTRANSPORTELEMENTTYPE.CORRECTPREDEFINEDTYPE' evaluates to FALSE
            Instance: OID: #46596
            Type: IfcTransportElementType
            References: SELF
            in file ..&#92;ifc_schemata&#92;ifc4x3_rc3.exp at line 11850
      </EccoErrorMessage>
</MVDEccoMessage>
```

File Encoding is correct:
```
#46596= IFCTRANSPORTELEMENTTYPE('0a5MZ59PD0wwcMc0ilz4oQ',$,'RHD_GM_Vessel:RHD_GM_Vessel',$,$,(#46593,#46590),(#46598),'339908',$,IFCTRANSPORTELEMENTNONFIXEDTYPEENUM(.VEHICLEMARINE.));
```

This one seems to be effecting the IfcElementType subtypes???

**Comment by AlexBrad1eyCT** [comment]
@pjanck, Do we have any developments on this latest checking error, i think once we sort this i can merge alot of my unit tests into main.
