### ISSUE TITLE
Errors with ifcCheckingTool: IfcCurveSegment in IFC4X3_RC3

### ISSUE THREAD

**Issue by BernhardWehrle** [bSI-InfraRoom/IFC-infra-unit-test#68]
Hi all
I am currently implementing the new IFC4X3RC3.
In the UC-IfcPavement unit test, now i get errors with IfcCurveSegment attributes.

In witch way must i set the attributes correct?

```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION (('ViewDefinition[Ifc4x3NotAssigned]'), '2.1');
FILE_NAME ('IFC_Export.ifc', '2021-03-13T07:33:03', (), ('AKG Software Consulting GmbH'), $, $, $);
FILE_SCHEMA (('IFC4X3_RC3'));
ENDSEC;
DATA;
...
#40 = IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE., #41, IfcNonNegativeLengthMeasure(0.), IfcNonNegativeLengthMeasure(14.142), #43);
#41 = IFCAXIS2PLACEMENT2D(#42, $);
#42 = IFCCARTESIANPOINT((513210., 5454110.));
#43 = IFCLINE(#44, #45);
#44 = IFCCARTESIANPOINT((0., 0.));
#45 = IFCVECTOR(#46, 14.142);
#46 = IFCDIRECTION((7.07106781188008E-1, 7.07106781208588E-1));
...
ENDSEC;
END-ISO-10303-21;
```

![IfcCurveSegment](https://user-images.githubusercontent.com/38724767/111022581-c4eaea80-83d3-11eb-9ad0-864a94bbc9b5.png)

**Comment by pjanck** [comment]
From the looks of it, the content of the IFC file was read incorrectly (the checker has `$` for attributes 2-5). Can you try writing the `IfcNonNegativeLengthMeasure` as all-caps and retry the procedure?

**Comment by BernhardWehrle** [comment]
What is all-caps? 
How can I do that with the IfcEngine.

Code now is:

// Station auf der Achse uebergeben
IfcHandle p_SegmentStart = IfcEngine.sdaiCreateADB(IfcEngine.sdaiREAL, ref P_Station);
IfcEngine.sdaiPutADBTypePath(p_SegmentStart, 1, "IfcNonNegativeLengthMeasure");
IfcEngine.sdaiPutAttrBN(p_IfcCurveSegment, "SegmentStart", IfcEngine.sdaiADB, p_SegmentStart);

**Comment by pjanck** [comment]
Suggestion: 

    IfcEngine.sdaiPutADBTypePath(p_SegmentStart, 1, "IFCNONNEGATIVELENGTHMEASURE");

All-caps: all letters capitalized (A-Z instead of a-z).

**Comment by BernhardWehrle** [comment]
Sorry for the stupid question.
Greeat. 
Now i have 10 errors less
