### ISSUE TITLE
CrossSectionPositions : LIST [2:?] OF IfcCurveMeasureSelect in IFC4X3RC3

### ISSUE THREAD

**Issue by BernhardWehrle** [bSI-InfraRoom/IFC-infra-unit-test#70]
Hi all

I tried to create a value in CrossSectionPositions in in the way described below
But there is no output in the IFC-File. No idea whats wrong.

double station = 20.0;

IfcHandle ifcSectionedSolidHorizontal = 0;
ifcSectionedSolidHorizontal = CreateInstance("IfcSectionedSolidHorizontal");
IfcHandle crossSectionPositions = IfcEngine.sdaiCreateAggrBN(ifcSectionedSolidHorizontal, "CrossSectionPositions");

IfcHandle distanceAlong = IfcEngine.sdaiCreateADB(IfcEngine.sdaiREAL, ref station);
IfcEngine.sdaiPutADBTypePath(distanceAlong, 1, "IFCNONNEGATIVELENGTHMEASURE");
IfcEngine.sdaiAppend(crossSectionPositions, IfcEngine.sdaiINSTANCE, distanceAlong);

`#1 = IFCSECTIONEDSOLIDHORIZONTAL($, $, (), $);`

ENTITY IfcSectionedSolidHorizontal
SUBTYPE OF (IfcSectionedSolid);
  CrossSectionPositions : LIST [2:?] OF IfcCurveMeasureSelect;

**Comment by pjanck** [comment]
Perhaps @peterrdf would be able to help here?

**Comment by peterrdf** [comment]
Dear Bernhard Wehrle,

I tried to copy your code and think I found the issue. Please change the line:

    IfcEngine.sdaiAppend(crossSectionPositions, IfcEngine.sdaiINSTANCE, distanceAlong);

into:

    IfcEngine.sdaiAppend(crossSectionPositions, IfcEngine.sdaiADB, distanceAlong);

The following code in C++ works overhere:

	{
		int_t model = sdaiOpenModelBN(0, 0, "IFC4x3");

		double	station = 20.0;
		int_t	ifcSectionedSolidHorizontal = 0;
		ifcSectionedSolidHorizontal = sdaiCreateInstanceBN(model, "IfcSectionedSolidHorizontal");
		int_t	* crossSectionPositions = sdaiCreateAggrBN(ifcSectionedSolidHorizontal, "CrossSectionPositions");

		int_t	* distanceAlong = (int_t*) sdaiCreateADB(sdaiREAL, &station);
		sdaiPutADBTypePath(distanceAlong, 1, "IFCNONNEGATIVELENGTHMEASURE");
		sdaiAppend((int_t) crossSectionPositions, sdaiADB, distanceAlong);

		sdaiSaveModelBN(model, "c:\\__aa\\tst.ifc");
		sdaiCloseModel(model);
	}

If it does not fix your issue, please let me know.

Best regards,

Peter.

*EDIT: Markdown syntax.*

**Comment by BernhardWehrle** [comment]
Thanks for the quick help.
Now it  works fine.
`#63 = IFCSECTIONEDSOLIDHORIZONTAL(#35, (#64, #67), (IFCNONNEGATIVELENGTHMEASURE(0.), IFCNONNEGATIVELENGTHMEASURE(14.142)), .T.);`
