### ISSUE TITLE
Pull request #71 IFC error

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-infra-unit-test#73]
See #71 : I get the following error from KIT checker for the alignment file:

`#56=IFCSHAPEREPRESENTATION(#55,'Axis','Curve2D',(#50))`

> where rule 'IFCSHAPEREPRESENTATION.CORRECTITEMSFORTYPE' evaluates to FALSE

`#107=IFCSHAPEREPRESENTATION(#55,'Axis','Curve3D',(#106))`

> where rule 'IFCSHAPEREPRESENTATION.CORRECTITEMSFORTYPE' evaluates to FALSE

*EDIT: markdown formatting*

**Comment by pjanck** [comment]
Perhaps [this](https://github.com/bSI-InfraRoom/IFC-infra-unit-test/pull/71/files#r597494434) could be the reason?

**Comment by larswik** [comment]
What exactly do you mean with this?

**Comment by pjanck** [comment]
Well, it's not valid STEP syntax, so it could be, that the reader has problems with figuring out, what entity it is, and thus flags the shape representation as false. This is just a wild guess.

**Comment by pjanck** [comment]
Ok, I see you've updated the IFC file to remove the error. Do you still get the same error, though?

**Comment by larswik** [comment]
I ran the KIT checker locally on a new version of the file (which I hadn't updated here - hence the confusion). The errors refer to the file that is currently uploaded.

**Comment by larswik** [comment]
I can't see what is wrong. The first refers to the horizontal alignment which refers to the IfcCompositeCurve which starts with a 2D line. The second refers to the vertical alignment which refers to an IfcGradientCurve which starts with a curve segment/IfcPolynomialCurve.

**Comment by pjanck** [comment]
Then, I'm really confused. I come to the same conclusions as you.

Looking at the code below, though: there is no `DERIVE: Dim` parameter specified that would return `Segments[0].Dim` or something similar. So it makes sense, that the checker returns false.

https://github.com/bSI-InfraRoom/IFC-Specification/blob/64f1fc0e8cdf8aba82d2b99a423ddefae2f5a2ba/IFC4x3_RC3.exp#L5105-L5119

**Comment by pjanck** [comment]
Fixed in the recent updates to the schema and checker.
