### ISSUE TITLE
Handle older IFC files as input?

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-infra-unit-test#89]
In the case with Indiana DoT unit tests, I have a couple of IFC4 input files that when checking with the KIT checker reports "application library not found". My own file created with IFC 4.3 using these files as input checks ok.
Check pull request [RumbleStrip-INDOT](https://github.com/bSI-InfraRoom/IFC-infra-unit-test/pull/88).

**Comment by pjanck** [comment]
IFC4 files are very welcome! The checker ignores them, though.
